Repository SuriyaaVijay/HacktoberFest2023, pull requests merged in 2023-10, with the labels that each got.

#15 Added LeetCode Problem 2873 and 2874 Solutions with Explanations and C++ Code.
  CONTRIBUTORS.md
  LeetCode Problems/2873. Maximum Value of an Ordered Triplet I/2873. Maximum Value of an Ordered Triplet I.cpp
  LeetCode Problems/2873. Maximum Value of an Ordered Triplet I/README.md
  LeetCode Problems/2874. Maximum Value of an Ordered Triplet II/2874. Maximum Value of an Ordered Triplet II.cpp
  LeetCode Problems/2874. Maximum Value of an Ordered Triplet II/README.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#14 Binary search algo in python by ineedtochangemyusername
  Programming Languages/binary_search.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#12 Create Contribution.md
  Contribution.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#5 Add files via upload
  LeetCode Problems/Monotonic_Array.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#17 React based CryptoCurrency Tracker
  MERN/Crypto Wizard/README.md
  MERN/Crypto Wizard/package-lock.json
  MERN/Crypto Wizard/package.json
  MERN/Crypto Wizard/public/banner2.jpg
  MERN/Crypto Wizard/public/favicon.ico
  MERN/Crypto Wizard/public/index.html
  MERN/Crypto Wizard/public/logo192.png
  MERN/Crypto Wizard/public/logo512.png
  MERN/Crypto Wizard/public/manifest.json
  MERN/Crypto Wizard/public/robots.txt
  MERN/Crypto Wizard/src/App.css
  MERN/Crypto Wizard/src/App.js
  MERN/Crypto Wizard/src/CryptoContext.js
  MERN/Crypto Wizard/src/components/CoinInfo.jsx
  MERN/Crypto Wizard/src/components/CoinsTable.jsx
  MERN/Crypto Wizard/src/components/Footer.css
  MERN/Crypto Wizard/src/components/Footer.jsx
  MERN/Crypto Wizard/src/components/Header.jsx
  MERN/Crypto Wizard/src/components/SelectButton.jsx
  MERN/Crypto Wizard/src/components/banner/Banner.jsx
  MERN/Crypto Wizard/src/components/banner/Carousel.jsx
  MERN/Crypto Wizard/src/config/api.js
  MERN/Crypto Wizard/src/config/data.js
  MERN/Crypto Wizard/src/index.css
  MERN/Crypto Wizard/src/index.js
  MERN/Crypto Wizard/src/pages/CoinPage.jsx
  MERN/Crypto Wizard/src/pages/Homepage.jsx
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#21 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#50 Add Leetcode problem solution 1095
  CONTRIBUTORS.md
  LeetCode Problems/1095. Find in Mountain Array.java
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#51 Add leetcode problem solution 04
  CONTRIBUTORS.md
  LeetCode Problems/4. Median Of Two Sorted Arrays.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#46 added python program for leap year
  Programming Languages/fibonacci_series.py
  Python/leap_year.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#20 Arranged existing files into folder and created folders for C++ and Python
  Programming Languages/.vscode/c_cpp_properties.json
  Programming Languages/.vscode/launch.json
  Programming Languages/.vscode/settings.json
  Programming Languages/C++/Topological Sort.cpp
  Programming Languages/Python/Info.md
  Programming Languages/Python/binary_search.py
  Programming Languages/Python/simple-linear-regressioin-python.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#19 Create 20. Valid Paranthesis
  LeetCode Problems/20. Valid Paranthesis
Labels: hacktoberfest, hacktoberfest2023

#25 added a leetcode problem
  Contribution.md
  LeetCode Problems/10. Regular Expression Matching/Readme.md
  LeetCode Problems/10. Regular Expression Matching/RegularExpressionMatching.cpp
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#30 Update README.md
  README.md
Labels: hacktoberfest

#43 Main
  .gitignore
  Programming Languages/C/helloHacktoberfest.c
Labels: hacktoberfest

#42 Create find_de_difference.cpp
  LeetCode Problems/find_de_difference.cpp
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#63 Create Bubblesort.cpp
  Algorithms/Bubblesort.cpp
Labels: hacktoberfest, hacktoberfest2023

#67 42.Trapping Rain Water
  LeetCode Problems/42.Trapping Rain Water/42.Trapping Rain Water.cpp
Labels: hacktoberfest

#57 Create ValidParentheses.cpp
  LeetCode Problems/ValidParentheses.cpp
Labels: hacktoberfest

#69 Added Image Resizer Project under Web Development
  Web Development/Image Resizer/main.js
  Web Development/Image Resizer/package-lock.json
  Web Development/Image Resizer/package.json
  Web Development/Image Resizer/preload.js
  Web Development/Image Resizer/readme
  Web Development/Image Resizer/renderer/about.html
  Web Development/Image Resizer/renderer/css/style.css
  Web Development/Image Resizer/renderer/images
  Web Development/Image Resizer/renderer/index.html
  Web Development/Image Resizer/renderer/js/renderer.js
  Web Development/Image Resizer/renderer/logo.svg
Labels: hacktoberfest

#72 Added Stack and Queue in DSA
  Algorithms/Stack.c
  Algorithms/queue.c
Labels: hacktoberfest

#148 Create towerofhanoi.py
  towerofhanoi.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted
